import argparse
import sys
import os
import math
from collections import Counter
import itertools
from scapy.all import PcapReader, ICMP, IP, Raw
from scapy.layers.inet6 import IPv6, ICMPv6EchoRequest, ICMPv6EchoReply

# --- COLOR AND BANNER SETUP ---
try:
    from colorama import init, Fore, Style

    C_CRIT = Fore.RED + Style.BRIGHT
    C_WARN = Fore.YELLOW + Style.BRIGHT
    C_ANOMALY = Fore.MAGENTA + Style.BRIGHT
    C_INFO = Fore.CYAN
    C_RESET = Style.RESET_ALL
    C_GREEN = Fore.GREEN
    init(autoreset=True)
except ImportError:
    C_CRIT = C_WARN = C_ANOMALY = C_INFO = C_GREEN = C_RESET =""

def print_banner():
    """Prints the ASCII art banner and tool name."""
    banner = f"""{C_GREEN}
  _____ _____ __  __ _____                 _ _ _             
 |_   _/ ____|  \\/  |  __ \\ /\\            | (_) |            
   | || |    | \\  / | |__) /  \\  _   _  __| |_| |_ ___  _ __ 
   | || |    | |\\/| |  ___/ /\\ \\| | | |/ _` | | __/ _ \\| '__|
  _| || |____| |  | | |  / ____ \\ |_| | (_| | | || (_) | |   
 |_____\\_____|_|  |_|_| /_/    \\_\\__,_|\\__,_|_|\\__\\___/|_|   
                                                             
                                                               
                                                                  
            -- ICMP Tunneling & Exfiltration Auditor --
                   -- V 1.0 by Fabio Zolin --                   
    {C_RESET}"""
    print(banner)


# --- DATA STRUCTURES ---

class ICMPStats:
    """Class to keep track of all counters and metrics for the ICMP packets analysis."""
    def __init__(self):
        self.total_packets = 0
        self.large_payloads = 0
        self.high_entropy = 0
        self.asymmetric_payloads = 0
        self.other_types = 0
        self.suspicious_ips = Counter()
        self.asymmetric_ips = Counter()
        self.packet_volume_per_ip = Counter()

class ICMPTracker:
    """
    Class to keep track of pending Echo Requests. 
    The Reply payload must be perfectly identical to the Request payload.
    """
    def __init__(self, max_size = 10000, cleanup_chunk=1000):
        # The key will be a tuple: (source_ip, destination_ip, icmp_id, icmp_seq)
        # The value will be the raw payload in bytes.
        self.pending_requests = {}
        self.max_size = max_size
        self.cleanup_chunk = cleanup_chunk
    
    def add_request(self, key, payload):
        self.pending_requests[key] = payload
        # If we hit the high watermark, perform a bulk eviction
        if len(self.pending_requests) > self.max_size:
            # itertools.islice efficiently grabs the first N keys without loading the whole dict
            # In Python 3.7+, dicts maintain insertion order, so these are guaranteed to be the oldest
            keys_to_delete = list(itertools.islice(self.pending_requests.keys(), self.cleanup_chunk))
            
            for k in keys_to_delete:
                del self.pending_requests[k]


# --- ENTROPY CALCULATORS ---

def calculate_shannon_entropy(payload_bytes):
    """
    Calculates the classical Shannon entropy on raw bytes.
    Finds encrypted, compressed payloads or binary files (e.g., executables or C2 beacons).
    """
    if not payload_bytes:
        return 0.0
    
    entropy = 0
    total_bytes = len(payload_bytes)
    byte_counts = Counter(payload_bytes)
    
    for count in byte_counts.values():
        probability = count / total_bytes
        entropy -= probability * math.log2(probability)
        
    return entropy

def calculate_delta_entropy(payload_bytes):
    """
    Calculates the differential entropy (on the mathematical jumps between bytes).
    Serves to eliminate false positives generated by standard diagnostic pings 
    (which are sequential or repetitive).
    """
    if len(payload_bytes) <= 1:
        return 0.0
        
    # 1. Calculate the absolute distances between a byte and the previous one
    deltas = []
    for i in range(1, len(payload_bytes)):
        delta = abs(payload_bytes[i] - payload_bytes[i-1])
        deltas.append(delta)
        
    # 2. Apply Shannon entropy to the list of distances
    entropy = 0
    total_deltas = len(deltas)
    delta_counts = Counter(deltas)
    
    for count in delta_counts.values():
        probability = count / total_deltas
        entropy -= probability * math.log2(probability)
        
    return entropy

# --- White List Loading ---
def load_whitelist(filepath):
    """Loads IPs from a text file into a fast-lookup set."""
    whitelist = set()
    if filepath:
        if os.path.isfile(filepath):
            with open(filepath, 'r') as f:
                for line in f:
                    ip = line.strip()
                    # Ignore empty lines and comments
                    if ip and not ip.startswith('#'):
                        whitelist.add(ip)
            print(f"{C_INFO}[INFO]{C_RESET} Loaded {len(whitelist)} IPs into the whitelist.")
        else:
            print(f"{C_WARN}[WARNING]{C_RESET} Whitelist file '{filepath}' not found. Proceeding without it.")
    return whitelist

# --- CORE ROUTING & ANALYSIS ---

def analyze_echo_request(packet, stats, tracker, config, is_ipv6):
    """
    Analyzes outbound ICMP traffic (Type 8).
    Looks for oversized payloads, high entropy (data exfiltration) 
    and updates the tracker for asymmetry verification.
    """
    ip_layer = packet[IPv6] if is_ipv6 else packet[IP]
    icmp_layer = packet[ICMPv6EchoRequest] if is_ipv6 else packet[ICMP]

    ip_src = ip_layer.src
    ip_dst = ip_layer.dst
    
    # 1. Volumetric Tracking (Flooding / C2 Beaconing)
    stats.packet_volume_per_ip[ip_src] += 1
    
    # 2. Raw Payload Extraction
    # If the ICMP packet lacks a Raw layer, the payload is empty (b'')
    payload_bytes = bytes(packet[Raw].load) if packet.haslayer(Raw) else b''
    payload_len = len(payload_bytes)
    
    # 3. Update the Tracker for the future Reply
    # The unique key consists of: Source IP, Destination IP, Ping ID, and Sequence
    # Note: ID and Seq are used by the OS to match the right response to the right request
    if hasattr(icmp_layer, 'id') and hasattr(icmp_layer, 'seq'):
        tracker_key = (ip_src, ip_dst, icmp_layer.id, icmp_layer.seq)
        tracker.add_request(tracker_key, payload_bytes)

    # If there is no payload, there is nothing else to analyze
    if payload_len == 0:
        return

    # --- DETECTION PHASE ---
    is_suspicious = False

    # Check A: Payload Size
    if payload_len > config['payload_size']:
        stats.large_payloads += 1
        is_suspicious = True
        if config['very_verbose']:
            print(f"{C_WARN}[WARNING]{C_RESET} Large ICMP Request from {ip_src} to {ip_dst}: {payload_len} bytes")

    # Check B: Entropy (Encryption / Binary Data)
    shannon_ent = calculate_shannon_entropy(payload_bytes)
    delta_ent = calculate_delta_entropy(payload_bytes)
    
    # Alert only if BOTH entropies exceed the threshold (zeros out false positives)
    if shannon_ent >= config['shannon_threshold'] and delta_ent >= config['delta_threshold']:
        stats.high_entropy += 1
        is_suspicious = True
        if config['verbose'] or config['very_verbose']:
            # Extract a safe snippet to print (max 80 bytes)
            safe_payload = repr(payload_bytes[:80])
            if len(payload_bytes) > 80:
                safe_payload += " ... [TRUNCATED]"
                
            print(f"{C_CRIT}[CRITICAL]{C_RESET} High Entropy ICMP Request from {ip_src} to {ip_dst}! (Shannon: {shannon_ent:.2f}, Delta: {delta_ent:.2f})")
            print(f"    -> Payload Snippet: {safe_payload}")            
            
    # If the packet triggered at least one alarm, flag the IP as suspicious
    if is_suspicious:
        stats.suspicious_ips[ip_src] += 1

def analyze_echo_reply(packet, stats, tracker, config, is_ipv6):
    """
    Analyzes inbound traffic (Type 0).
    Verifies that the payload matches the original Request 
    and checks for anomalous C2 commands.
    """
    ip_layer = packet[IPv6] if is_ipv6 else packet[IP]
    icmp_layer = packet[ICMPv6EchoReply] if is_ipv6 else packet[ICMP]

    payload_bytes = bytes(packet[Raw].load) if packet.haslayer(Raw) else b''
    payload_len = len(payload_bytes)
    ip_src = ip_layer.src
    ip_dst = ip_layer.dst
    is_suspicious = False

    # 1. Volumetric Tracking (Flooding Inbound)
    stats.packet_volume_per_ip[ip_src] += 1

    # 2. Asymmetry Verification (RFC 792 Violation)
    if hasattr(icmp_layer, 'id') and hasattr(icmp_layer, 'seq'):
        # IMPORTANT: Invert dst and src to find the original request in the dictionary
        original_request_key = (ip_dst, ip_src, icmp_layer.id, icmp_layer.seq)
        
        # If the original request exists in memory, compare the payloads
        if original_request_key in tracker.pending_requests:
            original_payload = tracker.pending_requests[original_request_key]
            
            if original_payload != payload_bytes:
                is_suspicious = True
                stats.asymmetric_payloads += 1
                stats.asymmetric_ips[ip_src] += 1
                stats.asymmetric_ips[ip_dst] += 1
                if config['verbose'] or config['very_verbose']:
                    print(f"{C_CRIT}[CRITICAL]{C_RESET} Asymmetric ICMP Reply from {ip_src} to {ip_dst} (ID: {icmp_layer.id}, Seq: {icmp_layer.seq})")
                    print(f"  -> Outbound Payload: {len(original_payload)} bytes")
                    print(f"  -> Inbound Payload:  {payload_len} bytes")
            
            # To prevent RAM clogging, delete the original request after verification
            del tracker.pending_requests[original_request_key]

    if payload_len == 0:
        return

    # 3. Check A: Payload Size (Inbound)
    if payload_len > config['payload_size']:
        stats.large_payloads += 1
        is_suspicious = True
        if config['very_verbose']:
            print(f"{C_WARN}[WARNING]{C_RESET} Large ICMP Reply from {ip_src} to {ip_dst}: {payload_len} bytes")

    # 4. Check B: Entropy (Inbound - Commands from C2)
    shannon_ent = calculate_shannon_entropy(payload_bytes)
    delta_ent = calculate_delta_entropy(payload_bytes)
    
    if shannon_ent >= config['shannon_threshold'] and delta_ent >= config['delta_threshold']:
        stats.high_entropy += 1
        is_suspicious = True
        if config['verbose'] or config['very_verbose']:
            safe_payload = repr(payload_bytes[:80])
            if len(payload_bytes) > 80:
                safe_payload += " ... [TRUNCATED]"
                
            print(f"{C_CRIT}[CRITICAL]{C_RESET} High Entropy ICMP Reply from {ip_src} to {ip_dst}! (Shannon: {shannon_ent:.2f}, Delta: {delta_ent:.2f})")
            print(f"    -> Payload Snippet: {safe_payload}")            
            
    # If the packet is anomalous, mark the C2 as suspicious
    if is_suspicious:
        stats.suspicious_ips[ip_src] += 1

def analyze_other_types(packet, stats, config):
    ip_src = packet[IP].src
    ip_dst = packet[IP].dst
    icmp_type = packet[ICMP].type
    
    payload_bytes = bytes(packet[Raw].load) if packet.haslayer(Raw) else b''
    payload_len = len(payload_bytes)

    # Grouping types by their real-world behavior
    network_infrastructure_types = [5, 9, 10, 12] # Redirects, Router Discovery, etc.
    error_quoting_types = [3, 11] # Unreachable, Time Exceeded

    stats.other_types += 1
    is_suspicious = False

    # 1. Unknown / Obsolete Types (Direct Alarm)
    if icmp_type not in network_infrastructure_types and icmp_type not in error_quoting_types:
        if not config['no_types']:
            is_suspicious = True
            if config['verbose'] or config['very_verbose']:
                print(f"{C_ANOMALY}[ANOMALY]{C_RESET} Unusual ICMP Type {icmp_type} detected from {ip_src} to {ip_dst}!")

    # 2. Error Types (3, 11) - Check for size, but be cautious of entropy
    elif icmp_type in error_quoting_types:
        # Check A: Size
        if payload_len > config['payload_size']:
            stats.large_payloads += 1
            is_suspicious = True
            if config['very_verbose']:
                print(f"{C_WARN}[WARNING]{C_RESET} Large payload in ICMP Type {icmp_type} from {ip_src}: {payload_len} bytes")

        # Check B: Entropy (Warning: May flag dropped HTTPS/TLS packets!)
        if payload_len > 0:
            shannon_ent = calculate_shannon_entropy(payload_bytes)
            delta_ent = calculate_delta_entropy(payload_bytes)
            
            if shannon_ent >= config['shannon_threshold'] and delta_ent >= config['delta_threshold']:
                # We don't mark is_suspicious = True here to avoid blacklisting IPs just for dropping TLS packets, 
                # but we still log it for the analyst to investigate.
                stats.high_entropy += 1
                if config['verbose'] or config['very_verbose']:
                    safe_payload = repr(payload_bytes[:80])
                    if len(payload_bytes) > 80:
                        safe_payload += " ... [TRUNCATED]"
                        
                    print(f"{C_WARN}[NOTICE]{C_RESET} High Entropy in Error ICMP Type {icmp_type} from {ip_src}. (Could be a dropped encrypted packet or hidden C2).")
                    print(f"    -> Payload Snippet: {safe_payload}")

    # 3. Infrastructure Types (5, 9, 10, 12) - Ignore payloads, they are naturally large/varied
    else:
        if config['very_verbose']:
            print(f"{C_INFO}[INFO]{C_RESET} Legitimate Infrastructure ICMP Type {icmp_type} from {ip_src}.")

    if is_suspicious:
        stats.suspicious_ips[ip_src] += 1
# --- REPORTING ---

def print_analysis_report(stats, config):
    """Formats and prints the final analysis report."""
    print("\n" + "="*55)
    print("      ICMP TUNNELING & EXFILTRATION REPORT")
    print("="*55)

    print(f"\n{C_INFO}[INFO]{C_RESET} Global Metrics:")
    print(f"    - Total ICMP Packets Analyzed: {stats.total_packets}")
    print(f"    - Large Payloads (> {config['payload_size']} bytes):  {stats.large_payloads}")
    print(f"    - High Entropy (Encrypted/C2): {stats.high_entropy}")
    print(f"    - Asymmetric Payloads (RFC 792): {stats.asymmetric_payloads}")
    print(f"    - Anomalous/Other ICMP Types:  {stats.other_types}")

    print(f"\n{C_WARN}Volume Analysis{C_RESET} (Threshold: {config['volume_limit']} pkts):")
    # Filter only the IPs that exceeded the volume threshold
    flooders = {ip: count for ip, count in stats.packet_volume_per_ip.items() if count > config['volume_limit']}
    if flooders:
        for ip, count in sorted(flooders.items(), key=lambda x: x[1], reverse=True):
            print(f"{C_WARN}    [*]{C_RESET} {ip} sent {count} packets (Possible Beaconing/Flooding)")
    else:
        print("    - No IPs exceeded the volume threshold.")

    print(f"\n{C_CRIT} Suspicious Hosts {C_RESET}(Payload / Entropy / Anomalies):")
    if stats.suspicious_ips:
        # Show the top 10 most malicious IPs
        for ip, count in stats.suspicious_ips.most_common(10):
            print(f"    - {ip}: flagged {count} times")
    else:
        print("    - No suspicious payload activity detected.")

    print(f"\n{C_CRIT} [CRITICAL]{C_RESET} Asymmetric Payload Offenders (Definite C2):")
    if stats.asymmetric_ips:
        for ip, count in stats.asymmetric_ips.most_common():
            print(f"{C_CRIT}    [!]{C_RESET} {ip}: involved in {count} asymmetric exchanges")
    else:
        print("    - No asymmetric payloads detected.")

    print("\n" + "="*55 + "\n")


def process_icmp_packet(packet, stats, tracker, config):
    """
    Core engine (The Router): verifies the packet is ICMP and sends it to the right analysis function.
    """
    is_ipv4 = packet.haslayer(IP) and packet.haslayer(ICMP)
    is_ipv6_req = packet.haslayer(IPv6) and packet.haslayer(ICMPv6EchoRequest)
    is_ipv6_rep = packet.haslayer(IPv6) and packet.haslayer(ICMPv6EchoReply)

    # 1. Security Tollbooth: if there is no IP or ICMP layer, discard the packet immediately.
    if not (is_ipv4 or is_ipv6_req or is_ipv6_rep):
        # Note: If you want to analyze "other" IPv6 types, you'd add them here
        return

    
    
    #Whitelist check 
    ip_layer = packet[IP] if is_ipv4 else packet[IPv6]
    if ip_layer.src in config['whitelist'] or ip_layer.dst in config['whitelist']:
        return
    
    # Add a packet to the global counter if not from whitelisted ip
    stats.total_packets += 1
    
    # 2. Extract the ICMP type and send to the correct function
    if is_ipv4:
        icmp_type = packet[ICMP].type
        if icmp_type == 8:
            analyze_echo_request(packet, stats, tracker, config, is_ipv6=False)
        elif icmp_type == 0:
            analyze_echo_reply(packet, stats, tracker, config, is_ipv6=False)
        else:
            analyze_other_types(packet, stats, config)
            
    elif is_ipv6_req:
        analyze_echo_request(packet, stats, tracker, config, is_ipv6=True)
        
    elif is_ipv6_rep:
        analyze_echo_reply(packet, stats, tracker, config, is_ipv6=True)


# --- ORCHESTRATOR ---

def analyze_pcap(pcap_file, config):
    """Orchestrator: validates the file, initializes data structures and iterates on packets."""
    if not os.path.isfile(pcap_file):
        print(f"{C_CRIT}[ERROR]{C_RESET} The file '{pcap_file}' doesn't exist or the path is wrong.")
        sys.exit(1)

    print(f"{C_INFO}[INFO]{C_RESET} Starting ICMP file analysis: {pcap_file}...")
    print(f"{C_WARN}[WAIT]{C_RESET} Parsing packets and analyzing entropy (this may take a while)...")
    
    # Structs initialization
    stats = ICMPStats()
    tracker = ICMPTracker()
    
    
    packet_counter = 0  # Global counter
    # PCAP reading
    with PcapReader(pcap_file) as packets:
        for packet in packets:
            packet_counter += 1
            process_icmp_packet(packet, stats, tracker, config)
            
            # --- PROGRESS INDICATOR ---
            # Update the screen every 10000 packets to avoid slowing down execution
            if packet_counter % 10000 == 0:
                print(f"\r[~] {C_INFO}Scanning PCAP... {packet_counter} total packets processed.", end="", flush=True)
            
    # When done, clear the line and print completion
    print(f"\r[+] Done! Scanned {packet_counter} packets. Found {stats.total_packets} ICMP packets.       ")
    
    # Print the final report
    print_analysis_report(stats, config)


def main():
    print_banner()
    # argparse setup
    parser = argparse.ArgumentParser(description="PCAP analyzer to detect ICMP tunneling and data exfiltration.")
    
    # Required argument
    parser.add_argument("-f", "--file", help="Path to the .pcap file to analyze", required=True)
    
    # Variable thresholds
    parser.add_argument("-s", "--size", help="Max allowed ICMP payload size in bytes before flagging (default: 64, raise to 110 if there's CISCO devices giving false positives)", type=int, default=64)
    parser.add_argument("-et", "--entropy", help="Minimum Shannon entropy score before flagging (default: 4.0)", type=float, default=4.0)
    parser.add_argument("-dt", "--delta", help="Minimum Delta entropy score before flagging (default: 2.5)", type=float, default=2.5)
    parser.add_argument("-vl", "--volume", help="Max number of ICMP packets per IP before flagging flooding/beaconing (default: 1000)", type=int, default=1000)
    parser.add_argument("-nt", "--no_types", help="Turns off flagging of IPs using unusual or deprecated ICMP types, still checks the contents for malicious payloads", action="store_true")
    # Verbosity levels
    parser.add_argument("-v", "--verbose", help="Enable verbose mode, displays individual alerts", action="store_true")
    parser.add_argument("-vv", "--very_verbose", help="Enable very verbose mode, displays all warnings and standard pings", action="store_true")
    # Whitelist
    parser.add_argument("-wl", "--whitelist", help="Path to .txt file containing whitelisted ip addresses, one per line.", type = str)
    
    args = parser.parse_args()
    
    # Config dictionary
    config = {
        'file': args.file,
        'payload_size': args.size,
        'shannon_threshold': args.entropy,
        'delta_threshold': args.delta,
        'volume_limit': args.volume,
        'no_types' : args.no_types,
        'whitelist' : load_whitelist(args.whitelist),
        'verbose': True if args.very_verbose else args.verbose,
        'very_verbose': args.very_verbose
    }

    
    # Likely false positives warnings
    if config['payload_size'] < 32:
        print(f"{C_WARN}[WARNING]{C_RESET} The payload size threshold is very low (< 32 bytes). Expect false positives from standard pings.")
        
    if config['shannon_threshold'] < 3.0 or config['delta_threshold'] < 1.5:
        print(f"{C_WARN}[WARNING]{C_RESET} Entropy thresholds are low. Expect false positives.")

    analyze_pcap(config['file'], config)


if __name__ == "__main__":
    main()